### PR TITLE
Bump etcdctl and etcd-wrapper to 3.3.25

### PR DESCRIPTION
**Pull request by sayanchowdhury**
# Bump etcdctl and etcd-wrapper to 3.3.25

# How to use

`emerge-amd64-usr dev-db/etcdctl`
`emerge-amd64-usr app-admin/etcd-wrapper`

# Testing done
http://localhost:9091/job/os/job/manifest/893/

### CODE REVIEW

**Review by t-lo — APPROVED** [review]
LGTM, thank you!

Testing done:
- built a qemu image based on Alpha 2605.0.0 plus branch `sayan/bump-etcd-etcdctl-to-3.3.25`
- ssh'd into the image and ran
   ```
   localhost ~ # etcdctl -v
   etcdctl version: 3.3.25
   API version: 2
   localhost ~ # systemctl start etcd-member
   localhost ~ # rkt list
   UUID		APP	IMAGE NAME			STATE	CREATED		STARTED	      
    NETWORKS
   f8573a06	etcd	quay.io/coreos/etcd:v3.3.25	running	3 minutes ago	3 minutes ago	
   localhost ~ # etcdctl cluster-health
   member 8e9e05c52164694d is healthy: got healthy result from http://localhost:2379
   cluster is healthy
   ```

**Comment by t-lo** [comment]
@sayanchowdhury please also cherry-pick for `flatcar-2605`.

**Comment by sayanchowdhury** [comment]
@t-lo Yes, I usually add the labels this PR would go into.

**Comment by sayanchowdhury** [comment]
Picked to `flatcar-2605`

**Pull request merged**
