### PR TITLE
app-emulation/containerd: update manifest

### PR DESCRIPTION
**Pull request by tormath1**
asset must have been silently updated since the tagging of
the release.

Signed-off-by: Mathieu Tortuyaux <mtortuyaux@microsoft.com>

## Testing done

```
emerge-amd64-usr -f containerd
```

CI: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4404/cldsv/

<hr>

Not sure we need a change log entry:
- [ ] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)

To be cherry-picked to:
- flatcar-3087
- flatcar-3066
- flatcar-3033
- flatcar-lts-2605

### CODE REVIEW

**Comment by t-lo** [comment]
LGTM in general, could you please amend the commit message to include a pointer to both https://github.com/containerd/containerd/discussions/6382 and https://github.com/google/ko/issues/315#issuecomment-783718564 ?

**Comment by tormath1** [comment]
@t-lo thanks, commit updated - I would just wait for the CI to confirm it builds `containerd` correctly again before merging.

**Review by t-lo — APPROVED** [review]
Verified the size and new checksums with a fresh download from the origin project (https://github.com/containerd/containerd/releases/tag/v1.5.8).
LGTM pending CI test.

**Review by dongsupark — APPROVED** [review]

**Review by sayanchowdhury — APPROVED** [review]

**Review by krnowak — APPROVED** [review]
I'd say let's merge it now, since the failure happened during building torcx store in packages matrix. Currently the build is past image matrix, so it works fine.

**Comment by tormath1** [comment]
cherry-picked to:
* flatcar-3087
* flatcar-3066
* flatcar-3033

**Pull request merged**
