### PR TITLE
sys-kernel/bootengine: bump to fix the sysroot-boot service race

### PR DESCRIPTION
**Pull request by krnowak**
Fixes https://github.com/flatcar-linux/Flatcar/issues/83.

This is a follow up from https://github.com/flatcar-linux/bootengine/pull/12.

Fixes a race between switching root and unmounting a boot mountpoint with a tool existing only in the old root.

# How to use

The repro is described in the issue linked above.

# Testing done

Same as in the PR linked above.

### CODE REVIEW

**Comment by krnowak** [comment]
Is this a candidate for cherry-picking for the rest of the branches?

**Comment by pothos** [comment]
Yes, this should be cherry-picked to `flatcar-master`, `flatcar-master-alpha`, `flatcar-master-beta`, `flatcar-build-2513.0.0`

**Comment by krnowak** [comment]
Updated the commit. Thanks.

**Comment by krnowak** [comment]
Cherry picks done too.

**Pull request merged**
