### PR TITLE
sys-apps/texinfo: Sync with gentoo

### PR DESCRIPTION
**Pull request by krnowak**
This is to get rid of EAPI 5 from the package.

CI: http://localhost:9091/job/os/job/manifest/3647/cldsv/

### CODE REVIEW

**Comment by krnowak** [comment]
CI passed.

**Comment by tormath1** [comment]
`sys-apps/texinfo` is one the SDK required package too: https://github.com/flatcar-linux/portage-stable/blob/82751b135f3ef5b6c876849812144743c7f8af03/scripts/bootstrap.sh#L334-L338. Do you think it's worth to run a SDK build too ?

**Comment by krnowak** [comment]
> `sys-apps/texinfo` is one of the SDK required packages too: https://github.com/flatcar-linux/portage-stable/blob/82751b135f3ef5b6c876849812144743c7f8af03/scripts/bootstrap.sh#L334-L338. Do you think it's worth to run a SDK build too ?

Thanks for pointing this out. I'll schedule one.

**Comment by krnowak** [comment]
There's an all-full build for this PR and for the perl update PR: http://localhost:9091/job/os/job/manifest/3654

**Review by sayanchowdhury — APPROVED** [review]
LGTM, the tests are green too. Can we squash the commits for dropping the changes not needed?
The `README.md` is really helpful.

**Comment by krnowak** [comment]
> LGTM, the tests are green too. Can we squash the commits for dropping the changes not needed?
> The `README.md` is really helpful.

Thanks. :) Will squash then merge.

**Pull request merged**
