### PR TITLE
sys-kernel: Enable elastic network adatper module for arm64

### PR DESCRIPTION
**Pull request by lht**
# Enable AWS ENA kernel module for arm64

Having problem get the EC2 ARM based instances (tried both A1 and M6 instances) running. The log suggests the network is not up.

```
Oct 06 04:41:01 localhost ignition[902]: GET http://169.254.169.254/2009-04-04/user-data: attempt #28
Oct 06 04:41:01 localhost ignition[902]: GET error: Get "http://169.254.169.254/2009-04-04/user-data": dial tcp 169.254.169.254:80: connect: network is unreachable
Oct 06 04:41:05 localhost ignition[902]: failed to fetch config: unable to fetch resource in time
```

# How to use

Rebuild the AMI and launch an ARM based EC2 instance.

# Testing done 

Not tested.

I've tried to Follow https://docs.flatcar-linux.org/os/sdk-modifying-flatcar/ for building arm64 images, but failed at step of running the `setup_board` script.

### CODE REVIEW

**Comment by pothos** [comment]
Thanks for the PR, I will start a test build (from a temporary copy of your branch). I'll give you the results and can also share the image.

Maybe there are even some other kernel options missing depending on the instance type.

What error did you ran into with the local SDK?

**Comment by lht** [comment]
Thanks @pothos for the swift response!

I got errors like below when running `setup_board`.
```
!!! Error fetching binhost package info from 'https://storage.googleapis.com/flatcar-jenkins/developer/boards/arm64-usr/    arm64-usr/alpha/pkgs/'
!!! HTTP Error 404: Not Found
```

[Full log is attached](https://github.com/flatcar-linux/coreos-overlay/files/5338377/setup-board-build-log.txt)

**Comment by pothos** [comment]
You are working on the `main` branches and the default manifest, or? Did you set up the nightly package store with the following command?

```
# in the scripts folder
./set_version --dev-board --board-version arm64-usr/main-nightly --dev-sdk --sdk-version sdk-main-nightly
```

**Comment by lht** [comment]
I followed the doc and run the exact below commands before entering the chroot.
```
cork create
cork enter
```
IIUC, this will use main branch and alpha release?

As shown in the attached log file. I have also run the exact `set_version` command as you pasted.

**Comment by lht** [comment]
Sorry, I actually didn't use the correct flag when running the `set_version` script. Your command `./set_version --dev-board --board-version arm64-usr/main-nightly --dev-sdk --sdk-version sdk-main-nightly` works! Thanks!

**Comment by pothos** [comment]
Thanks, was about to say that it looks like the branch wasn't resolved. In `/build/arm64-usr/etc/portage/make.conf` there should be something like
```
PORTAGE_BINHOST=" https://storage.googleapis.com/flatcar-jenkins/developer/boards/arm64-usr/2020.10.07+dev-main-nightly-1171/pkgs/
https://storage.googleapis.com/flatcar-jenkins/developer/boards/arm64-usr/2020.10.07+dev-main-nightly-1171/toolchain/"
```

**Comment by lht** [comment]
I build an image and imported as AMI with `ore`. Turns out it works! There are a few failed systemd units though.

```
Flatcar Container Linux by Kinvolk developer (2020.10.07+dev-main-nightly-1171+2020-10-07-0942)
Failed Units: 2
  ignition-disks.service
  polkit.service
core@localhost ~ $ uname -a
Linux localhost 5.8.13-flatcar #1 SMP PREEMPT Wed Oct 7 04:37:10 -00 2020 aarch64 GNU/Linux

core@localhost ~ $ sudo systemctl status ignition-disks
● ignition-disks.service
     Loaded: not-found (Reason: Unit ignition-disks.service not found.)
     Active: failed (Result: exit-code) since Wed 2020-10-07 11:38:36 UTC; 3min 48s ago
   Main PID: 902 (code=exited, status=1/FAILURE)

Oct 07 11:38:27 localhost ignition[902]: GET http://169.254.169.254/2009-04-04/user-data: attempt #27
Oct 07 11:38:27 localhost ignition[902]: GET error: Get "http://169.254.169.254/2009-04-04/user-data": dial tcp 169.254.169.254:80: connect: network is unreach>
Oct 07 11:38:32 localhost ignition[902]: GET http://169.254.169.254/2009-04-04/user-data: attempt #28
Oct 07 11:38:32 localhost ignition[902]: GET error: Get "http://169.254.169.254/2009-04-04/user-data": dial tcp 169.254.169.254:80: connect: network is unreach>
Oct 07 11:38:36 localhost ignition[902]: failed to fetch config: unable to fetch resource in time
Oct 07 11:38:36 localhost systemd[1]: ignition-disks.service: Main process exited, code=exited, status=1/FAILURE
Oct 07 11:38:36 localhost ignition[902]: failed to acquire config: unable to fetch resource in time
Oct 07 11:38:36 localhost systemd[1]: ignition-disks.service: Failed with result 'exit-code'.
Oct 07 11:38:36 localhost ignition[902]: Ignition failed: unable to fetch resource in time
Oct 07 11:38:36 localhost systemd[1]: Failed to start Ignition (disks).
core@localhost ~ $ sudo systemctl status polkit.service
● polkit.service - Authorization Manager
     Loaded: loaded (/usr/lib/systemd/system/polkit.service; static; vendor preset: disabled)
     Active: failed (Result: signal) since Wed 2020-10-07 11:38:46 UTC; 3min 47s ago
       Docs: man:polkit(8)
    Process: 1432 ExecStart=/usr/lib/polkit-1/polkitd --no-debug (code=killed, signal=SEGV)
   Main PID: 1432 (code=killed, signal=SEGV)

Oct 07 11:38:46 localhost systemd[1]: Starting Authorization Manager...
Oct 07 11:38:46 localhost polkitd[1432]: Started polkitd version 0.113
Oct 07 11:38:46 localhost systemd[1]: polkit.service: Main process exited, code=killed, status=11/SEGV
Oct 07 11:38:46 localhost systemd[1]: polkit.service: Failed with result 'signal'.
Oct 07 11:38:46 localhost systemd[1]: Failed to start Authorization Manager.
```

**Comment by pothos** [comment]
Yes, you were faster, I wanted to share the image link and test results but the tests didn't fully run after it detected that some units failed. That the machine starts is already splendid, thanks a lot.

**Review by pothos — APPROVED** [review]

**Comment by pothos** [comment]
The `ignition-disks.service` did not fail here, just the polkit.service. (The tests for amd64 did run as usual.)

**Comment by lht** [comment]
Awesome, thanks for the help!

**Pull request merged**
