### PR TITLE
sys-kernel/coreos-sources: revert commit which breaks networking on M4 instances

### PR DESCRIPTION
**Pull request by jepio**
# sys-kernel/coreos-sources: revert commit which breaks networking on M4 instances

We bisected m4 networking failure down to a commit that has already been backported to all stable kernels. Revert the commit while upstream discussions happen.

## How to use

If the ami from the test run is still around:
```
./bin/kola spawn --aws-type m4.large --board amd64-usr  --aws-iam-profile jenkins-test --platform=aws  --aws-ami=ami-03ecf733c5ca3afeb --aws-region=us-west-2 --verbose --aws-credentials-file ~/.aws/credentials
```

## Testing done

Successfully tested here: http://jenkins.infra.kinvolk.io:8080/job/os/job/kola/job/aws/1242/tapResults/.

- [x] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)

### CODE REVIEW

**Comment by pothos** [comment]
What target branch is this?

**Comment by jepio** [comment]
This one is for flatcar-3033, and I wanted to merge it after https://github.com/flatcar-linux/coreos-overlay/pull/1715 is merged.

**Comment by pothos** [comment]
Ok, a changelog entry would be good, too

**Comment by jepio** [comment]
> What target branch is this?

Wanted to see this work:

> Base automatically changed from linux-5.10.105-flatcar-3033 to flatcar-3033

**Review by pothos — APPROVED** [review]

**Pull request merged**
