### PR TITLE
dev-db/etcdctl: Bump to 3.3.24

### PR DESCRIPTION
**Pull request by sayanchowdhury**
Signed-off-by: Sayan Chowdhury <sayan@kinvolk.io>

# dev-db/etcdctl: Bump to 3.3.24

This commit updates etcdctl to 3.3.24 and backports a patch to fix the fileutil import path from 3.3.25  release etcd-io/etcd#12246 

# How to use
`emerge-amd64-usr dev-db/etcdctl

# Testing done
http://localhost:9091/job/os/job/manifest/886/

### CODE REVIEW

**Comment by dongsupark** [comment]
etcd [v3.3.25](https://github.com/etcd-io/etcd/releases/tag/v3.3.25) seems to already have the import path fix.

**Comment by sayanchowdhury** [comment]
Yes, I've even prepared a branch for 3.3.25 upgrade and triggered a dev build. In case, that fails, we will go ahead with the 3.3.24 release.

**Comment by dongsupark** [comment]
Oh, interesting. I see.

**Review by dongsupark — APPROVED** [review]

**Comment by sayanchowdhury** [comment]
Closing this PR as the 3.3.25 is merged in #551

**Pull request closed without merging**
