### PR TITLE
Update net-misc/google-cloud-sdk to 355.0.0

### PR DESCRIPTION
**Pull request by krnowak**
This is to get rid of the python2 dependency.

~~I also install additional tool - bq (it's for big query stuff).~~

CI: ~~http://localhost:9091/job/os/job/manifest/3517~~ http://localhost:9091/job/os/job/manifest/3532/cldsv/

### CODE REVIEW

**Comment by krnowak** [comment]
CI passed.

**Comment by krnowak** [comment]
I dropped the dependency on pyopenssl and rerun the CI. Seems to work. pyopenssl was used only for signurl command which we only use with gsutil coming from docker image. Also added some README with some notes about the package.

CI: http://localhost:9091/job/os/job/manifest/3570/cldsv/

**Review by jepio — APPROVED** [review]
Love it. Getting rid of pyopenssl is also a preqrequisite of the openssl upgrade.

**Comment by dongsupark** [comment]
If we can delete pyopenssl, then we can also delete `dev-python/cryptography`. :+1:

**Comment by krnowak** [comment]
Yeah, I'm actually doing it in https://github.com/flatcar-linux/portage-stable/pull/214, but it's still a draft.

**Pull request merged**
