### PR TITLE
Update flatcar-master-edge

### PR DESCRIPTION
**Pull request by pothos**
Merge flatcar-master into flatcar-master-edge.

### CODE REVIEW

**Comment by pothos** [comment]
Still building locally, will upload the images when done.

**Comment by dongsupark** [comment]
Note: we also need to merge e04e8177f154b125b5fdd92e7e22805696290a81 to flatcar-master-edge.

**Comment by pothos** [comment]
Yes, done. I am currently updating Rust to 1.37.

**Comment by dongsupark** [comment]
I have pushed a commit to fix kernel build failures with amd64.

**Comment by pothos** [comment]
TODO: The Docker build has a cross compilation error and searches for the wrong compiler triple `aarch64-linux-gnu` instead of `aarch64-cros-linux-gnu`.

**Comment by dongsupark** [comment]
Fixed the docker cross-build issue.

**Pull request merged**
