### PR TITLE
Add ARM64 support for cifs-utils, realmd, sssd, adcli, go-tspi

### PR DESCRIPTION
**Pull request by t-lo**
This change adds multiple tools to ARM64 which were formerly only
present in the X86-64 image.

Added for ARM64:

        net-fs/cifs-utils
        sys-auth/realmd
        sys-auth/sssd
        app-admin/adcli
        app-crypt/go-tspi

This leaves only the xenserver-pv-version and xenstore packages exclusively on X86-64.

The change un-masks keywords `amd64` and `arm64` for `sys-libs/liburing-2.1-r2` and keyword `arm64` for `dev-libs/ding-libs-0.6.1-r1`, overwriting Gentoo upstream defaults in portage-stable.

Partially fixes https://github.com/flatcar-linux/Flatcar/issues/689.
Fixes https://github.com/flatcar-linux/Flatcar/issues/690.

Requires https://github.com/flatcar-linux/portage-stable/pull/334 .

## How to use

Check out branch. Build the image.
```shell
./run_sdk_container -t 
   ./ build_packages --board=arm64-usr
   ./build_image --board=arm64-usr
   ./image_to_vm.sh ...
```

Then launch the image and check for binaries / libraries.
```shell
./flatcar_production_qemu_uefi.sh
[...]
core@localhost ~ $ sssd --version
2.3.1
core@localhost ~ $ sudo -i
root@localhost ~ # /usr/libexec/realmd --help
Usage:
  realmd [OPTION?] realmd
[...]
root@localhost ~ # adcli
usage: adcli command <args>...
[...]
root@localhost ~ # cifs.upcall -v
version: 6.13
```

## Testing done

Built the image locally and checked for binaries.

- [X] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)

### CODE REVIEW

**Review by jepio — APPROVED** [review]
OK. Running CI

**Comment by jepio** [comment]
CI looks good, go ahead and merge

**Comment by t-lo** [comment]
Rebased the PR to include @mtougeron 's original work from https://github.com/flatcar-linux/coreos-overlay/pull/1883. It's the same changes but now with the proper attribution. Merging.

**Comment by mtougeron** [comment]
> Rebased the PR to include @mtougeron 's original work from #1883. It's the same changes but now with the proper attribution. Merging.

oh wow, thank you, you didn't need to do that. I appreciate it. :)

**Pull request merged**
