### PR TITLE
app-emulation: bump docker-runc to 1.0.0_rc10 for alpha

### PR DESCRIPTION
**Pull request by dongsupark**
Upgrade docker-runc to 1.0.0-rc10 to avoid several race issues, as well as to address a bunch of security issues.

Get rid of unnecessary patches.
Remove old docker-runc version 1.0.0-rc2_p136.
Use Go 1.13 for runc and containerd, to build the latest versions at all.

### CODE REVIEW

**Comment by pothos** [comment]
The content of `app-torcx/docker/files/` needs to be adjusted, too.

**Comment by pothos** [comment]
… and `app-arch/torcx/files/`.

**Comment by dongsupark** [comment]
Brought back the old docker versions, 1.12 and 17.03, for the upcoming Alpha release.
We will revisit the Docker/torcx profiles issue next week again.

**Comment by dongsupark** [comment]
Fixed other build failures.
(Fixes to fixes to fixes..)

**Pull request merged**
