### PR TITLE
sys-kernel: backport hyper-v PCI patches from v5.17-rc1

### PR DESCRIPTION
**Pull request by jepio**
# backport hyper-v PCI patches from v5.17-rc1

## How to use

`emerge-arm64-usr -av coreos-{sources,modules,kernel}`

## Testing done

Build and boot tested.

- [X] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)

### CODE REVIEW

**Comment by krnowak** [comment]
You checked the changelog checkbox, but there isn't any changelog. Did you forget to add it?

**Comment by jepio** [comment]
My intention was to mark that this change does not need an accompanying changelog entry.

**Comment by krnowak** [comment]
> My intention was to mark that this change does not need an accompanying changelog entry.

Alright, I'd just drop it then next time to avoid confusion. And maybe add "no changelog needed" or something.

**Review by krnowak — APPROVED** [review]
Looks good.

**Comment by jepio** [comment]
Tests passed on amd64.

**Pull request merged**
