### PR TITLE
sys-kernel/kernel-modules: Add some configs

### PR DESCRIPTION
**Pull request by krnowak**
`net-libs/libnetfilter_cthelper` needs CONFIG_NF_CT_NETLINK_HELPER.
CONFIG_NET_VRF was requested by a user. CONFIG_KEY_DH_OPERATIONS is
useful for `sys-apps/keyutils`. Rest of the added configs are
dependencies.

- [x] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)

CI: http://localhost:9091/job/os/job/manifest/4441/cldsv/

### CODE REVIEW

**Comment by krnowak** [comment]
CI passed.

**Comment by pothos** [comment]
> [ ] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)

Looks good, can you formulate the "changes" entries please?

**Comment by krnowak** [comment]
> > [ ] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
> 
> Looks good, can you formulate the "changes" entries please?

Thanks, done.

**Review by tormath1 — APPROVED** [review]
Looks good :)

**Pull request merged**
