### PR TITLE
Bump linux kernel and related software to 5.15

### PR DESCRIPTION
**Pull request by krnowak**
This updates linux kernel to 5.15.4, sys-fs/btrfs-progs to 5.15.1 and adds some keywords for packages updated in portage-stable.

Update sys-process/audit to 3.0.6 so it actually builds with the new kernel headers (they dropped `linux/ipx.h`, and audit got a fix to detect the situation).

To be merged together with https://github.com/flatcar-linux/portage-stable/pull/251.

CI: http://localhost:9091/job/os/job/manifest/4263/cldsv/

### CODE REVIEW

**Comment by krnowak** [comment]
I'll probably try also bumping a bunch of other packages that are bound to kernel (sys-fs/btrfs-progs, sys-kernel/linux-headers, sys-apps/iproute2, dev-util/strace (this one seems to be separate from kernel, but releases are aligned with kernel), dev-util/perf).

**Comment by krnowak** [comment]
CI passed.

**Comment by jepio** [comment]
Could you add a changelog file? I'm sure we'll miss the systemd update otherwise.

**Review by jepio — APPROVED** [review]
Looks good. It's not strictly necessary for us to keep headers/perf/iproute in sync but newer versions are always welcome.

**Comment by krnowak** [comment]
> Could you add a changelog file? I'm sure we'll miss the systemd update otherwise.

Will do.

**Comment by krnowak** [comment]
> Looks good. It's not strictly necessary for us to keep headers/perf/iproute in sync but newer versions are always welcome.

Thanks. About keeping stuff in sync - I remember once inspektor gadget folks complained that the headers we had were too old. They got updated since then, but still.

**Comment by dongsupark** [comment]
Can you please update `KV_MAIN` in `.github/workflows/kernel-releases-main.yml`?

**Comment by krnowak** [comment]
> Can you please update `KV_MAIN` in `.github/workflows/kernel-releases-main.yml`?

Arf, there's always something to forget. Thanks, will do.

**Comment by krnowak** [comment]
Changelogs added, github workflow updated, merging.

Changelogs have a tiny bit different format (prepended a dash to get a bullet list in rendered markdown), I'll file a PR later to fix the README.

**Pull request merged**
