### PR TITLE
update containerd to 1.5.11

### PR DESCRIPTION
**Pull request by jepio**
# update containerd to 1.5.11

Containerd 1.5.11 fixes a CVE, and the checksum of 1.5.10 sources has changed so we need to either refresh the checksum, or update. We choose to update.

To be picked to flatcar-3139.

## How to use

[ describe what reviewers need to do in order to validate this PR ]

## Testing done

[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]

- [x] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)

### CODE REVIEW

**Comment by jepio** [comment]
Tests running: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/

**Review by JAORMX — APPROVED** [review]

**Comment by jepio** [comment]
CI passed, all tests passed except ignitionv3 which accidentally ran for this branch.

**Comment by tormath1** [comment]
> CI passed, all tests passed except ignitionv3 which accidentally ran for this branch.

@jepio Ignitionv3 tests have only a minimum version - should we exclude beta/stable channels for extra safety ?

**Comment by jepio** [comment]
> > CI passed, all tests passed except ignitionv3 which accidentally ran for this branch.
> 
> @jepio Ignitionv3 tests have only a minimum version - should we exclude beta/stable channels for extra safety ?

No, no worry, its a matter of version matching.

**Pull request merged**
